# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('O', 'Open'), ('P', 'Processed'), ('C', 'Cancelled'), ('M', 'Modified')], default='O', max_length=2)),
                ('order_date', models.DateField()),
                ('ship_date', models.DateField()),
                ('customer_po', models.CharField(max_length=30)),
                ('contract', models.CharField(max_length=30)),
                ('isd_name', models.CharField(max_length=100)),
                ('isd_code', models.CharField(max_length=30)),
                ('sales_id', models.CharField(max_length=30, null=True)),
                ('salesperson', models.CharField(max_length=30, null=True)),
                ('address_line1', models.TextField(max_length=100)),
                ('address_line2', models.TextField(max_length=100, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_phone', models.CharField(max_length=30, null=True)),
                ('contact_fax', models.CharField(max_length=30, null=True)),
                ('contact_email', models.CharField(max_length=100, null=True)),
                ('owed_by_isd', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('extra', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('quantity_uom', models.CharField(choices=[('BK', 'Book'), ('KT', 'Kit'), ('SP', 'Software Product'), ('EA', 'EACH')], max_length=2)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_price_code', models.CharField(choices=[('03', 'Contract'), ('04', 'No Charge')], max_length=2)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ship_date', models.DateField(null=True)),
                ('isbn', models.CharField(max_length=30)),
                ('student_edition', models.CharField(max_length=30)),
                ('student_edition_cost', models.CharField(max_length=30)),
                ('school_district_owes', models.CharField(max_length=30)),
                ('original_quantity', models.IntegerField(null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('modified', models.BooleanField(default=False)),
                ('added', models.BooleanField(default=False)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.PurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isd_name', models.CharField(max_length=100)),
                ('isd_code', models.CharField(max_length=30)),
                ('district_enrollment', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('region', models.IntegerField(blank=True, null=True)),
                ('sales_id', models.CharField(max_length=10)),
                ('rsm', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line1', models.TextField(max_length=100)),
                ('address_line2', models.TextField(blank=True, max_length=100, null=True)),
                ('address_line3', models.TextField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_fax', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('ag', models.BooleanField(default=False)),
                ('fcs', models.BooleanField(default=False)),
                ('ti', models.BooleanField(default=False)),
                ('bm', models.BooleanField(default=False)),
                ('careers', models.BooleanField(default=False)),
                ('dag', models.BooleanField(default=False)),
                ('dfcs', models.BooleanField(default=False)),
                ('dti', models.BooleanField(default=False)),
                ('dbm', models.BooleanField(default=False)),
                ('dcareers', models.BooleanField(default=False)),
                ('careerdemo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['isd_name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingInvoice',
            fields=[
                ('invoice_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('invoice_status', models.CharField(choices=[('I', 'Imported'), ('P', 'Processed'), ('A', 'Accepted'), ('E', 'Accepted with Error'), ('R', 'Rejected')], default='I', max_length=2)),
                ('invoice_date', models.DateField()),
                ('actual_ship_date', models.DateField()),
                ('boxes', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tracking_number', models.CharField(max_length=100)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_invoice', to='core.PurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('quantity_uom', models.CharField(choices=[('BK', 'Book'), ('KT', 'Kit'), ('SP', 'Software Product')], max_length=2)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actual_ship_date', models.DateField(null=True)),
                ('isbn', models.CharField(max_length=30)),
                ('student_edition', models.CharField(max_length=30)),
                ('student_edition_cost', models.CharField(max_length=30)),
                ('school_district_owes', models.CharField(max_length=30, null=True)),
                ('shipping_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.ShippingInvoice')),
            ],
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('events', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='salesperson',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.School'),
        ),
    ]
