# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='batch_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_ICEV',
            field=models.BooleanField(default=False),
        ),
    ]
