# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170207_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
