# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170209_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginvoice',
            old_name='invoice_amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='shippinginvoice',
            name='carrier_code',
            field=models.CharField(default='111', max_length=30),
        ),
        migrations.AddField(
            model_name='shippinginvoice',
            name='carrier_name',
            field=models.CharField(default='UPS', max_length=100),
        ),
        migrations.AddField(
            model_name='shippinginvoice',
            name='isd_code',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippinginvoice',
            name='isd_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippinginvoiceline',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippinginvoiceline',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
