# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170404_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginvoiceline',
            name='actual_ship_date',
            field=models.DateField(),
        ),
    ]
